#include <stdio.h>
#include <string.h>

#include "core/mock_backend.h"
#include "gateway/gateway_coordinator.h"
#include "gateway/gateway_orchestration_mock.h"

static unsigned int checks,failed;
#define CHECK(x) do{++checks;if(!(x)){++failed;printf("FAIL line %u: %s\n",(unsigned)__LINE__,#x);}}while(0)
const unsigned char coordinator_layout[sizeof(gateway_coordinator_t)]={0};
const unsigned char coordinator_health_layout[sizeof(gateway_coordinator_health_t)]={0};

typedef struct load_plan {gateway_config_result_t result;gateway_config_source_t source;gateway_persistent_config_t config;unsigned int calls;} load_plan_t;
typedef struct fixture {gateway_coordinator_t coordinator;gateway_run_control_t run;gateway_port_binding_t bindings[8];mock_backend_t backend[8];gateway_transport_mock_t transport[8];load_plan_t load;unsigned int provider_calls;unsigned int provider_seen_port;unsigned int attach_calls;int provider_fail;int attach_fail;} fixture_t;

static gateway_config_result_t load_config(void*context,const char*d,gateway_persistent_config_t*c,gateway_config_source_t*s)
{load_plan_t*p=(load_plan_t*)context;(void)d;++p->calls;if(p->result==GATEWAY_CONFIG_OK||p->result==GATEWAY_CONFIG_ABSENT){*c=p->config;*s=p->source;}return p->result;}
static int provide_bindings(void*context,const gateway_port_config_t*p,gateway_port_binding_t*b)
{fixture_t*f=(fixture_t*)context;++f->provider_calls;f->provider_seen_port=p[0].endpoint_port;if(f->provider_fail)return-1;memcpy(b,f->bindings,sizeof(f->bindings));return 0;}
static int attach_bindings(void*context,gateway_controller_t*c){fixture_t*f=(fixture_t*)context;(void)c;++f->attach_calls;return f->attach_fail?-1:0;}
static void fixture_prepare(fixture_t*f,gateway_config_result_t result,gateway_config_source_t source)
{unsigned int i;memset(f,0,sizeof(*f));gateway_run_control_init(&f->run);gateway_persistent_defaults(&f->load.config);f->load.result=result;f->load.source=source;for(i=0;i<8U;++i){mock_backend_init(&f->backend[i]);gateway_transport_mock_init(&f->transport[i]);f->bindings[i].backend_ops=mock_backend_ops();f->bindings[i].backend_context=&f->backend[i];f->bindings[i].transport_ops=gateway_transport_mock_ops();f->bindings[i].transport_context=&f->transport[i];}CHECK(gateway_coordinator_init(&f->coordinator,"unused",&f->run,load_config,&f->load,provide_bindings,attach_bindings,f,0,10)==0);}
static void run_startup(fixture_t*f,core_tick_t limit)
{core_tick_t n;for(n=10;n<limit;++n){gateway_application_state_t s=f->coordinator.state;if(s==GATEWAY_APP_READY||s==GATEWAY_APP_DEGRADED||s==GATEWAY_APP_SAFE_MODE||s==GATEWAY_APP_FATAL_ERROR)return;gateway_coordinator_step(&f->coordinator,n);}}
static void run_shutdown(fixture_t*f,core_tick_t start)
{core_tick_t n;gateway_coordinator_request_shutdown(&f->coordinator,start);for(n=start;n<start+2100U&&f->coordinator.state!=GATEWAY_APP_STOPPED;++n)gateway_coordinator_step(&f->coordinator,n);}

static void all_ready_and_events(void)
{fixture_t f;gateway_coordinator_health_t h;gateway_startup_event_t e,previous;unsigned int i;fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_ACTIVE);run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_READY&&f.load.calls==1&&f.coordinator.controller_initialized&&f.coordinator.controller_start_called);gateway_coordinator_health(&f.coordinator,100,&h);CHECK(h.config_source==GATEWAY_CONFIG_SOURCE_ACTIVE&&h.enabled_ports==8&&h.ready_ports==8&&h.progress_percent==100&&h.error==GATEWAY_APP_ERROR_NONE);memset(&previous,0,sizeof(previous));for(i=0;i<gateway_coordinator_event_count(&f.coordinator);++i){CHECK(gateway_coordinator_event(&f.coordinator,i,&e)==0);CHECK(e.sequence>previous.sequence);CHECK(e.progress_percent>=previous.progress_percent);previous=e;}CHECK(e.progress_percent==100);for(i=0;i<8U;++i)CHECK(f.backend[i].opens==1&&f.transport[i].starts==1);run_shutdown(&f,101);CHECK(f.coordinator.state==GATEWAY_APP_STOPPED&&f.coordinator.cleanup_complete&&f.coordinator.controller_shutdown_called==1);for(i=0;i<8U;++i)CHECK(f.backend[i].stops==1&&f.transport[i].stops==1);gateway_coordinator_request_shutdown(&f.coordinator,300);CHECK(f.coordinator.controller_shutdown_called==1);}

static void sources_and_safe_mode(void)
{fixture_t f;gateway_coordinator_health_t h;unsigned int i;fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_BACKUP);run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_READY&&f.coordinator.config_source==GATEWAY_CONFIG_SOURCE_BACKUP);fixture_prepare(&f,GATEWAY_CONFIG_ABSENT,GATEWAY_CONFIG_SOURCE_DEFAULTS);run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_READY&&f.coordinator.config_source==GATEWAY_CONFIG_SOURCE_DEFAULTS);fixture_prepare(&f,GATEWAY_CONFIG_INVALID,GATEWAY_CONFIG_SOURCE_SAFE_MODE);run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_SAFE_MODE&&f.coordinator.error==GATEWAY_APP_ERROR_CONFIG_INVALID);gateway_coordinator_health(&f.coordinator,100,&h);CHECK(h.progress_percent==100&&h.enabled_ports==0&&h.ready_ports==0&&h.disabled_ports==8);for(i=0;i<8U;++i)CHECK(f.backend[i].opens==0&&f.transport[i].starts==0);run_shutdown(&f,101);CHECK(f.coordinator.state==GATEWAY_APP_STOPPED&&f.coordinator.cleanup_complete);fixture_prepare(&f,GATEWAY_CONFIG_IO_ERROR,GATEWAY_CONFIG_SOURCE_SAFE_MODE);run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_SAFE_MODE&&f.coordinator.error==GATEWAY_APP_ERROR_STORAGE_IO);fixture_prepare(&f,GATEWAY_CONFIG_UNSUPPORTED_VERSION,GATEWAY_CONFIG_SOURCE_SAFE_MODE);run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_SAFE_MODE&&f.coordinator.error==GATEWAY_APP_ERROR_CONFIG_UNSUPPORTED);}

static void isolated_failures(void)
{fixture_t f;gateway_coordinator_health_t h;unsigned int i;fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_ACTIVE);f.backend[1].open_failures_remaining=10000;f.backend[1].recovery_failures_remaining=10000;f.transport[3].start_failures_remaining=1;run_startup(&f,1200);CHECK(f.coordinator.state==GATEWAY_APP_DEGRADED);gateway_coordinator_health(&f.coordinator,1200,&h);CHECK(h.progress_percent==100&&h.ready_ports==6&&h.error_ports==2);for(i=0;i<8U;++i)if(i!=1U&&i!=3U)CHECK(f.coordinator.controller.ports[i].lifecycle==GATEWAY_PORT_READY);run_shutdown(&f,1201);CHECK(f.coordinator.state==GATEWAY_APP_STOPPED);fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_ACTIVE);for(i=0;i<8U;++i){f.backend[i].open_failures_remaining=10000;f.backend[i].recovery_failures_remaining=10000;}run_startup(&f,1200);CHECK(f.coordinator.state==GATEWAY_APP_DEGRADED);gateway_coordinator_health(&f.coordinator,1200,&h);CHECK(h.ready_ports==0&&h.error_ports==8&&h.progress_percent==100);}

static int failed_init(gateway_controller_t*c,const gateway_port_config_t*p,const gateway_port_binding_t*b){(void)c;(void)p;(void)b;return-1;}
static const gateway_controller_driver_t failing_driver={failed_init,gateway_controller_start,gateway_controller_step,gateway_controller_shutdown,gateway_controller_health};
static void fatal_partial_and_signal(void)
{fixture_t f;fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_ACTIVE);f.coordinator.controller_driver=&failing_driver;run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_FATAL_ERROR&&f.coordinator.error==GATEWAY_APP_ERROR_CONTROLLER_INIT&&!f.coordinator.controller_initialized);CHECK(f.coordinator.progress_numerator==GATEWAY_STARTUP_PROGRESS_TOTAL);gateway_coordinator_request_shutdown(&f.coordinator,100);CHECK(f.coordinator.state==GATEWAY_APP_STOPPED&&f.coordinator.cleanup_complete);fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_ACTIVE);while(f.coordinator.state!=GATEWAY_APP_STARTING_PORTS)gateway_coordinator_step(&f.coordinator,20);gateway_run_control_request_stop(&f.run);gateway_coordinator_step(&f.coordinator,21);CHECK(f.coordinator.state==GATEWAY_APP_SHUTTING_DOWN||f.coordinator.state==GATEWAY_APP_STOPPED);run_shutdown(&f,22);CHECK(f.coordinator.state==GATEWAY_APP_STOPPED&&f.coordinator.controller_shutdown_called==1);}

static void validation_and_incomplete_shutdown(void)
{fixture_t f;gateway_coordinator_health_t h;fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_ACTIVE);f.load.config.ports[1].uart_index=0;run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_SAFE_MODE&&f.coordinator.error==GATEWAY_APP_ERROR_CONFIG_INVALID);fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_ACTIVE);run_startup(&f,100);f.transport[2].stop_failures_remaining=1;run_shutdown(&f,101);CHECK(f.coordinator.state==GATEWAY_APP_STOPPED&&!f.coordinator.cleanup_complete&&f.coordinator.error==GATEWAY_APP_ERROR_SHUTDOWN_INCOMPLETE);gateway_coordinator_health(&f.coordinator,2200,&h);CHECK(!h.cleanup_complete&&h.error==GATEWAY_APP_ERROR_SHUTDOWN_INCOMPLETE);}

static void health_and_bounded_runtime(void)
{fixture_t f;gateway_coordinator_health_t h;unsigned int before,i;fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_ACTIVE);f.load.config.ports[7].enabled=0;run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_READY);f.transport[0].clients=2;f.coordinator.controller.ports[0].runtime.stats.accepted=5;f.coordinator.controller.ports[0].runtime.stats.completed=4;f.coordinator.controller.ports[0].runtime.stats.timeouts=1;f.coordinator.controller.ports[0].runtime.stats.recoveries=1;f.coordinator.controller.ports[0].runtime.stats.stale_responses=1;before=f.coordinator.controller.scheduler_steps;for(i=0;i<1000U;++i)gateway_coordinator_step(&f.coordinator,100U+i);CHECK(f.coordinator.controller.scheduler_steps==before+1000U);gateway_coordinator_health(&f.coordinator,1100,&h);CHECK(h.enabled_ports==7&&h.ready_ports==7&&h.disabled_ports==1&&h.clients==2&&h.accepted==5&&h.completed==4&&h.timeouts==1&&h.recoveries==1&&h.stale_responses==1&&h.uptime==1090);}

static void binding_configuration_boundary(void)
{fixture_t f;fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_ACTIVE);f.load.config.ports[0].endpoint_port=1602;run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_READY&&f.provider_calls==1&&f.attach_calls==1&&f.provider_seen_port==1602&&f.transport[0].endpoint==1602);fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_ACTIVE);f.provider_fail=1;run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_FATAL_ERROR&&f.coordinator.error==GATEWAY_APP_ERROR_BINDING_INIT&&!f.coordinator.controller_initialized);CHECK(f.coordinator.progress_numerator==GATEWAY_STARTUP_PROGRESS_TOTAL);fixture_prepare(&f,GATEWAY_CONFIG_OK,GATEWAY_CONFIG_SOURCE_ACTIVE);f.attach_fail=1;run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_FATAL_ERROR&&f.coordinator.error==GATEWAY_APP_ERROR_BINDING_INIT&&f.coordinator.controller_initialized&&!f.coordinator.controller_start_called);CHECK(f.coordinator.progress_numerator==GATEWAY_STARTUP_PROGRESS_TOTAL);}

static void real_absent_selection(const char*d)
{fixture_t f;unsigned int i;memset(&f,0,sizeof(f));gateway_run_control_init(&f.run);for(i=0;i<8U;++i){mock_backend_init(&f.backend[i]);gateway_transport_mock_init(&f.transport[i]);f.bindings[i].backend_ops=mock_backend_ops();f.bindings[i].backend_context=&f.backend[i];f.bindings[i].transport_ops=gateway_transport_mock_ops();f.bindings[i].transport_context=&f.transport[i];}CHECK(gateway_coordinator_init(&f.coordinator,d,&f.run,0,0,provide_bindings,0,&f,0,0)==0);run_startup(&f,100);CHECK(f.coordinator.state==GATEWAY_APP_READY&&f.coordinator.persistence_result==GATEWAY_CONFIG_ABSENT&&f.coordinator.config_source==GATEWAY_CONFIG_SOURCE_DEFAULTS);}

int main(int argc,char**argv){if(argc!=2)return 2;all_ready_and_events();sources_and_safe_mode();isolated_failures();fatal_partial_and_signal();validation_and_incomplete_shutdown();health_and_bounded_runtime();binding_configuration_boundary();real_absent_selection(argv[1]);printf("coordinator checks=%u failed=%u bytes=%u health=%u events=%u progress_total=%u\n",checks,failed,gateway_coordinator_memory_bytes(),(unsigned)sizeof(gateway_coordinator_health_t),GATEWAY_STARTUP_EVENT_CAPACITY,GATEWAY_STARTUP_PROGRESS_TOTAL);return failed?1:0;}
