#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include "diagnostics/gateway_diagnostics.h"

typedef struct output { char *data; size_t capacity, used; int truncated; } output_t;
static void append(output_t*o,const char*format,...){int n;va_list ap;if(o->truncated)return;va_start(ap,format);n=vsnprintf(o->data+o->used,o->capacity-o->used,format,ap);va_end(ap);if(n<0||(size_t)n>=o->capacity-o->used){o->used=o->capacity?o->capacity-1U:0U;o->truncated=1;}else o->used+=(size_t)n;}
static void raw_counts(output_t*o,const gateway_port_health_t*p,unsigned int index)
{
    const gateway_transport_diagnostics_t*d=&p->transport;
    if(p->config.transport!=TRANSPORT_RAW_TCP&&p->config.transport!=TRANSPORT_RAW_UDP)return;
    append(o,"port.%u.raw_network_rx=%u\nport.%u.raw_network_tx=%u\nport.%u.raw_serial_rx=%u\nport.%u.raw_serial_tx=%u\n",index,d->raw_network_received,index,d->raw_network_sent,index,d->raw_serial_read,index,d->raw_serial_written);
    append(o,"port.%u.raw_rejected_peers=%u\nport.%u.raw_discarded_serial=%u\nport.%u.raw_dropped_datagrams=%u\nport.%u.raw_stalls=%u\nport.%u.raw_io_errors=%u\n",index,d->raw_rejected_peers,index,d->raw_discarded_serial,index,d->tx_overflow,index,d->write_deadline_expired,index,d->gateway_path_unavailable);
}
static gateway_render_result_t finish(output_t*o,size_t*used){if(used)*used=o->used;return o->truncated?GATEWAY_RENDER_TRUNCATED:GATEWAY_RENDER_OK;}
static const char*app_state(gateway_application_state_t s){static const char*n[]={"BOOTSTRAP","LOADING_CONFIGURATION","SELECTING_CONFIGURATION","VALIDATING_CONFIGURATION","INITIALIZING_CONTROLLER","STARTING_PORTS","CHECKING_HEALTH","READY","DEGRADED","SAFE_MODE","SHUTTING_DOWN","STOPPED","FATAL_ERROR"};return (unsigned)s<sizeof(n)/sizeof(n[0])?n[s]:"UNKNOWN";}
static const char*source(gateway_config_source_t s){static const char*n[]={"ACTIVE","BACKUP","DEFAULTS","SAFE_MODE"};return (unsigned)s<4U?n[s]:"UNKNOWN";}
static const char*lifecycle(gateway_port_lifecycle_t s){static const char*n[]={"DISABLED","STARTING","READY","RECONFIGURING","ROLLING_BACK","STOPPING","DEGRADED","ERROR","WAIT NETWORK"};return (unsigned)s<9U?n[s]:"UNKNOWN";}
static const char*mode(serial_mode_t m){static const char*n[]={"RS232","RS485-2W","RS422","RS485-4W"};return (unsigned)m<4U?n[m]:"UNKNOWN";}
static const char*parity(parity_mode_t p){static const char*n[]={"NONE","EVEN","ODD"};return (unsigned)p<3U?n[p]:"UNKNOWN";}
static const char*transport(transport_type_t t){static const char*n[]={"MODBUS_TCP","MODBUS_UDP","MODBUS_RTU_UDP","RAW_TCP","RAW_UDP"};return (unsigned)t<5U?n[t]:"UNKNOWN";}
static const char*time_trust(gateway_time_trust_state_t t){static const char*n[]={"UNKNOWN","UNSYNCED","SYNCING","SYNCED","MANUAL","ERROR","HOLDOVER"};return (unsigned)t<7U?n[t]:"UNKNOWN";}
static const char*ntp_result(gateway_ntp_result_t r){static const char*n[]={"NOT_CONFIGURED","NOT_ATTEMPTED","IN_PROGRESS","SUCCEEDED","FAILED","TIMED_OUT","UNSUITABLE"};return (unsigned)r<7U?n[r]:"UNKNOWN";}

int gateway_diagnostics_capture(const gateway_application_t*a,gateway_diagnostic_snapshot_t*s){unsigned int i,n;if(!a||!s)return-1;memset(s,0,sizeof(*s));gateway_application_health(a,&s->application);s->schema_version=a->coordinator.selected.schema_version;n=gateway_coordinator_event_count(&a->coordinator);if(n>GATEWAY_STARTUP_EVENT_CAPACITY)n=GATEWAY_STARTUP_EVENT_CAPACITY;s->startup_event_count=n;for(i=0;i<n;++i)gateway_coordinator_event(&a->coordinator,i,&s->startup_events[i]);for(i=0;i<GATEWAY_PORT_COUNT;++i){const gateway_port_health_t*p=&s->application.coordinator.gateway.port[i];if(p->transactions.queue_high_water>s->queue_high_water)s->queue_high_water=p->transactions.queue_high_water;if(a->prepared_adapters&(1U<<i))s->uart[i]=a->adapters[i].uart.stats;}return 0;}
static int begin(output_t*o,char*b,size_t c){if(!o||!b||c==0U)return-1;o->data=b;o->capacity=c;o->used=0;o->truncated=0;b[0]='\0';return 0;}
#define gateway_diagnostics_render_summary render_summary_impl
#define gateway_diagnostics_render_port render_port_impl
#define gateway_diagnostics_render_configuration render_configuration_impl
#define gateway_diagnostics_render_system render_system_impl
#define gateway_diagnostics_render_startup render_startup_impl
#define gateway_diagnostics_render_support render_support_impl
gateway_render_result_t gateway_diagnostics_render_summary(const gateway_diagnostic_snapshot_t*s,char*b,size_t c,size_t*u){output_t o;unsigned i;if(!s||begin(&o,b,c))return GATEWAY_RENDER_INVALID;append(&o,"%s %s\nState: %s  Uptime: %lu ms\nConfig: %s  Progress: %u%%\nPorts: enabled=%u ready=%u error=%u disabled=%u clients=%u\n\nPort State       Serial        Endpoint                 Clients OK TO REC\n",s->application.product.name,s->application.product.version,app_state(s->application.coordinator.state),(unsigned long)s->application.coordinator.uptime,source(s->application.coordinator.config_source),s->application.coordinator.progress_percent,s->application.coordinator.enabled_ports,s->application.coordinator.ready_ports,s->application.coordinator.error_ports,s->application.coordinator.disabled_ports,s->application.coordinator.clients);for(i=0;i<GATEWAY_PORT_COUNT;++i){const gateway_port_health_t*p=&s->application.coordinator.gateway.port[i];append(&o,"P%u   %-11s %-8s/%-6lu %-15s:%-5u %7u %u %u %u\n",i+1U,lifecycle(p->lifecycle),mode(p->config.mode),p->config.baud,p->enabled?p->config.bind_address:"-",p->enabled?p->config.endpoint_port:0U,p->connected_clients,p->transactions.completed,p->transactions.timeouts,p->transactions.recoveries);}return finish(&o,u);}
gateway_render_result_t gateway_diagnostics_render_port(const gateway_diagnostic_snapshot_t*s,unsigned int index,char*b,size_t c,size_t*u){output_t o;const gateway_port_health_t*p;if(!s||index>=GATEWAY_PORT_COUNT||begin(&o,b,c))return GATEWAY_RENDER_INVALID;p=&s->application.coordinator.gateway.port[index];append(&o,"Port P%u\nenabled=%u\nuart=/dev/ttyM%u\nserial=%s %lu %u%s%u\ntransport=%s\nendpoint=%s:%u\nlifecycle=%s\nruntime_state=%u\nclients=%u\naccepted=%u\ncompleted=%u\ntimeouts=%u\nrecoveries=%u\nstale=%u\ncrc_failures=%u\nframing_failures=%u\nunit_mismatch=%u\nfunction_mismatch=%u\nleading_garbage=%u\nqueue_depth=%u\nqueue_high_water=%u\nlast_success_ms=%lu\nconfig_generation=%u\nlast_error=%s\n",index+1U,p->enabled,p->config.uart_index,mode(p->config.mode),p->config.baud,p->config.data_bits,parity(p->config.parity),p->config.stop_bits,transport(p->config.transport),p->config.bind_address,p->config.endpoint_port,lifecycle(p->lifecycle),(unsigned)p->runtime_state,p->connected_clients,p->transactions.accepted,p->transactions.completed,p->transactions.timeouts,p->transactions.recoveries,p->transactions.stale_responses,p->transport.crc_failures,p->transport.framing_failures,p->transport.unit_mismatches,p->transport.function_mismatches,p->transport.leading_garbage,p->transactions.queue_depth,p->transactions.queue_high_water,(unsigned long)p->transactions.last_success_at,p->config_generation,p->runtime_last_error[0]?p->runtime_last_error:"none");return finish(&o,u);}
gateway_render_result_t gateway_diagnostics_render_configuration(const gateway_diagnostic_snapshot_t*s,char*b,size_t c,size_t*u){output_t o;if(!s||begin(&o,b,c))return GATEWAY_RENDER_INVALID;append(&o,"Configuration\nsource=%s\npersistence_result=%u\nschema_version=%u\npath=%.180s\nsafe_mode_reason=%u\nbackup_used=%u\n",source(s->application.coordinator.config_source),(unsigned)s->application.coordinator.persistence_result,s->schema_version,s->application.configuration_directory,(unsigned)s->application.coordinator.error,s->application.coordinator.config_source==GATEWAY_CONFIG_SOURCE_BACKUP);return finish(&o,u);}
gateway_render_result_t gateway_diagnostics_render_system(const gateway_diagnostic_snapshot_t*s,char*b,size_t c,size_t*u){output_t o;if(!s||begin(&o,b,c))return GATEWAY_RENDER_INVALID;append(&o,"%s %s\nmodel=%s\nkernel=%s\narchitecture=%s\nword_bits=%u\nendianness=%s\nuptime_ms=%lu\ntime_trust=%s\nntp_enabled=%u\nntp_result=%s\nntp_server=%s\nntp_attempts=%u\nlast_ntp_attempt_ms=%lu\nlast_sync_ms=%lu\n",s->application.product.name,s->application.product.version,s->application.platform.model,s->application.platform.kernel,s->application.platform.architecture,s->application.platform.word_bits,s->application.platform.big_endian?"big":"little",(unsigned long)s->application.coordinator.uptime,time_trust(s->application.time.trust),s->application.time.ntp_enabled,ntp_result(s->application.time.last_ntp_result),s->application.time.ntp_server[0]?s->application.time.ntp_server:"none",s->application.time.ntp_attempts,(unsigned long)s->application.time.last_ntp_attempt,(unsigned long)s->application.time.last_sync);append(&o,"ntp_interval_hours=%u\nntp_test_active=%u\nntp_test_attempts=%u\nntp_network_deferred=%u\n",s->application.time.ntp_interval_hours,s->application.time.ntp_test_active,s->application.time.ntp_test_attempts,s->application.time.ntp_network_deferred);append(&o,"rtc_state=%s\nlast_rtc_save_ms=%lu\nrtc_save_failures=%u\nnext_ntp_attempt_ms=%lu\nntp_consecutive_failures=%u\n",gateway_rtc_state_name(s->application.time.rtc),(unsigned long)s->application.time.last_rtc_save,s->application.time.rtc_save_failures,(unsigned long)s->application.time.next_ntp_attempt,s->application.time.ntp_failures);return finish(&o,u);}
gateway_render_result_t gateway_diagnostics_render_startup(const gateway_diagnostic_snapshot_t*s,char*b,size_t c,size_t*u){output_t o;unsigned i;if(!s||begin(&o,b,c))return GATEWAY_RENDER_INVALID;append(&o,"Startup events (%u retained)\n",s->startup_event_count);for(i=0;i<s->startup_event_count;++i){const gateway_startup_event_t*e=&s->startup_events[i];append(&o,"seq=%u stage=%s result=%u progress=%u/%u (%u%%) port=%s%u error=%u\n",e->sequence,app_state(e->stage),(unsigned)e->result,e->progress_numerator,e->progress_denominator,e->progress_percent,e->port_index==GATEWAY_NO_PORT?"-":"P",e->port_index==GATEWAY_NO_PORT?0U:e->port_index+1U,(unsigned)e->error);}return finish(&o,u);}
gateway_render_result_t gateway_diagnostics_render_support(const gateway_diagnostic_snapshot_t*s,char*b,size_t c,size_t*u){output_t o;unsigned i;if(!s||begin(&o,b,c))return GATEWAY_RENDER_INVALID;append(&o,"product=%s\nversion=%s\nstate=%s\nconfig_source=%s\nprogress=%u\nschema_version=%u\ntime_trust=%s\nntp_result=%s\nntp_server=%s\nntp_attempts=%u\nlast_ntp_attempt_ms=%lu\nlast_sync_ms=%lu\n",s->application.product.name,s->application.product.version,app_state(s->application.coordinator.state),source(s->application.coordinator.config_source),s->application.coordinator.progress_percent,s->schema_version,time_trust(s->application.time.trust),ntp_result(s->application.time.last_ntp_result),s->application.time.ntp_server[0]?s->application.time.ntp_server:"none",s->application.time.ntp_attempts,(unsigned long)s->application.time.last_ntp_attempt,(unsigned long)s->application.time.last_sync);append(&o,"ntp_interval_hours=%u\nntp_test_active=%u\nntp_test_attempts=%u\nntp_network_deferred=%u\n",s->application.time.ntp_interval_hours,s->application.time.ntp_test_active,s->application.time.ntp_test_attempts,s->application.time.ntp_network_deferred);append(&o,"rtc_state=%s\nlast_rtc_save_ms=%lu\nrtc_save_failures=%u\nnext_ntp_attempt_ms=%lu\nntp_consecutive_failures=%u\n",gateway_rtc_state_name(s->application.time.rtc),(unsigned long)s->application.time.last_rtc_save,s->application.time.rtc_save_failures,(unsigned long)s->application.time.next_ntp_attempt,s->application.time.ntp_failures);for(i=0;i<GATEWAY_PORT_COUNT;++i){const gateway_port_health_t*p=&s->application.coordinator.gateway.port[i];append(&o,"port.%u.state=%s\nport.%u.endpoint=%s:%u\nport.%u.clients=%u\nport.%u.completed=%u\nport.%u.timeouts=%u\nport.%u.recoveries=%u\nport.%u.stale=%u\nport.%u.crc_failures=%u\nport.%u.framing_failures=%u\nport.%u.unit_mismatch=%u\nport.%u.function_mismatch=%u\nport.%u.leading_garbage=%u\n",i+1U,lifecycle(p->lifecycle),i+1U,p->enabled?p->config.bind_address:"-",p->enabled?p->config.endpoint_port:0U,i+1U,p->connected_clients,i+1U,p->transactions.completed,i+1U,p->transactions.timeouts,i+1U,p->transactions.recoveries,i+1U,p->transactions.stale_responses,i+1U,p->transport.crc_failures,i+1U,p->transport.framing_failures,i+1U,p->transport.unit_mismatches,i+1U,p->transport.function_mismatches,i+1U,p->transport.leading_garbage);raw_counts(&o,p,i+1U);}return finish(&o,u);}
#undef gateway_diagnostics_render_summary
#undef gateway_diagnostics_render_port
#undef gateway_diagnostics_render_configuration
#undef gateway_diagnostics_render_system
#undef gateway_diagnostics_render_startup
#undef gateway_diagnostics_render_support
static size_t bounded(size_t supplied,size_t maximum){return supplied<maximum?supplied:maximum;}
gateway_render_result_t gateway_diagnostics_render_summary(const gateway_diagnostic_snapshot_t*s,char*b,size_t c,size_t*u){return render_summary_impl(s,b,bounded(c,GATEWAY_DIAGNOSTIC_SUMMARY_MAX),u);}
gateway_render_result_t gateway_diagnostics_render_port(const gateway_diagnostic_snapshot_t*s,unsigned int p,char*b,size_t c,size_t*u){return render_port_impl(s,p,b,bounded(c,GATEWAY_DIAGNOSTIC_PORT_MAX),u);}
gateway_render_result_t gateway_diagnostics_render_configuration(const gateway_diagnostic_snapshot_t*s,char*b,size_t c,size_t*u){return render_configuration_impl(s,b,bounded(c,GATEWAY_DIAGNOSTIC_SUMMARY_MAX),u);}
gateway_render_result_t gateway_diagnostics_render_system(const gateway_diagnostic_snapshot_t*s,char*b,size_t c,size_t*u){return render_system_impl(s,b,bounded(c,GATEWAY_DIAGNOSTIC_SUMMARY_MAX),u);}
gateway_render_result_t gateway_diagnostics_render_startup(const gateway_diagnostic_snapshot_t*s,char*b,size_t c,size_t*u){return render_startup_impl(s,b,bounded(c,GATEWAY_DIAGNOSTIC_STARTUP_MAX),u);}
gateway_render_result_t gateway_diagnostics_render_support(const gateway_diagnostic_snapshot_t*s,char*b,size_t c,size_t*u){return render_support_impl(s,b,bounded(c,GATEWAY_DIAGNOSTIC_SUPPORT_MAX),u);}
unsigned int gateway_diagnostic_snapshot_bytes(void){return(unsigned int)sizeof(gateway_diagnostic_snapshot_t);}
