#include <stdio.h>
#include <string.h>
#include "launcher/gateway_startup_presentation.h"
#include "version.h"
static const char*state_name(gateway_application_state_t s){switch(s){case GATEWAY_APP_BOOTSTRAP:return"Starting";case GATEWAY_APP_LOADING_CONFIGURATION:return"Loading configuration";case GATEWAY_APP_SELECTING_CONFIGURATION:return"Selecting configuration";case GATEWAY_APP_VALIDATING_CONFIGURATION:return"Validating configuration";case GATEWAY_APP_INITIALIZING_CONTROLLER:return"Initializing controller";case GATEWAY_APP_CHECKING_HEALTH:return"Checking health";case GATEWAY_APP_READY:return"Ready";case GATEWAY_APP_DEGRADED:return"Degraded";case GATEWAY_APP_SAFE_MODE:return"Safe Mode";case GATEWAY_APP_FATAL_ERROR:return"Fatal Error";default:return"Starting ports";}}
static const char*result_name(gateway_startup_event_result_t r){switch(r){case GATEWAY_EVENT_SKIPPED:return"disabled";case GATEWAY_EVENT_FAILED:return"failed";case GATEWAY_EVENT_OK:return"ready";default:return"starting";}}
void gateway_startup_presentation_init(gateway_startup_presentation_t*p,gateway_splash_charset_t c){if(p){memset(p,0,sizeof(*p));p->charset=c;}}
int gateway_startup_presentation_render(gateway_startup_presentation_t*p,const gateway_application_t*a,size_t*used){gateway_application_health_t h;gateway_startup_event_t e;unsigned int percent,filled,i;char bar[3U*GATEWAY_SPLASH_BAR_WIDTH+1U],stage[64];int n;if(!p||!a||!used)return-1;gateway_application_health(a,&h);e=h.coordinator.last_event;percent=h.coordinator.progress_percent;if(percent<p->last_percent)percent=p->last_percent;if(percent>100U)percent=100U;filled=(percent*GATEWAY_SPLASH_BAR_WIDTH)/100U;bar[0]='\0';for(i=0;i<GATEWAY_SPLASH_BAR_WIDTH;++i){const char*x;if(p->charset==GATEWAY_SPLASH_UTF8)x=i<filled?"\xe2\x96\x88":"\xe2\x96\x91";else x=i<filled?"#":"-";strcat(bar,x);}if(e.port_index<GATEWAY_PORT_COUNT)snprintf(stage,sizeof(stage),"P%u %s",e.port_index+1U,result_name(e.result));else snprintf(stage,sizeof(stage),"%s",state_name(h.coordinator.state));n=snprintf(p->output,sizeof(p->output),"\n              %s\n               %s\n\n        %s\n        Linux %s | %s | %s Endian\n\n        [%s] %u%%\n\n        %s\n",FOURVRS_PRODUCT_NAME,FOURVRS_VERSION,h.platform.model,h.platform.kernel,h.platform.architecture,h.platform.big_endian?"Big":"Little",bar,percent,stage);if(n<0||(size_t)n>=sizeof(p->output))return-1;*used=(size_t)n;p->last_sequence=e.sequence;p->last_percent=percent;++p->renders;return 0;}
unsigned int gateway_startup_presentation_bytes(void){return(unsigned int)sizeof(gateway_startup_presentation_t);}
