'use strict';
const $=id=>document.getElementById(id), content=$('content');
let language=localStorage.getItem('language')||'EN', csrf='', page='', revision='', busy=false, networkTimer;
const words={Overview:'Обзор',Ports:'Порты',Network:'Сеть',Diagnostics:'Диагностика',System:'Система',About:'О системе',Save:'Сохранить',Review:'Проверить',Apply:'Применить',Keep:'Сохранить сеть',Revert:'Откатить',Enabled:'Включено',Disabled:'Выключено','Sign out':'Выйти',Password:'Пароль','One-time code':'Одноразовый код','Create administrator':'Создать администратора','Sign in':'Войти','Repeat password':'Повторите пароль'};
Object.assign(words,{'State':'Состояние','Serial mode':'Режим UART','Baud':'Скорость','Data bits':'Биты данных','Parity':'Чётность','None':'Нет','Even':'Чётная','Odd':'Нечётная','Stop bits':'Стоп-биты','Transport':'Транспорт','Bind IP':'Адрес привязки','Special baud':'Нестандартная скорость','Special baud value':'Значение скорости','Mode':'Режим','Static':'Статический','Netmask':'Маска','Gateway':'Шлюз','Default route':'Основной маршрут','Manual':'Вручную','DHCP DNS source':'Источник DNS DHCP','Default route':'Основной маршрут','Interface':'Интерфейс','Both':'Оба','Backlight':'Подсветка','Server':'Сервер','Stopped':'Остановлен','Starting':'Запускается','Running':'Работает','Failed':'Ошибка','Applying':'Применяется','Waiting for ports':'Ожидание портов','Confirm network':'Подтвердите сеть','Saving':'Сохранение','Rolling back':'Откат','Restoring ports':'Восстановление портов','Kept':'Сохранено','Reverted':'Отменено','Unavailable':'Недоступно','Idle':'Готово','Uncertain':'Требуется проверка','Rollback failed':'Ошибка отката'});
const t=s=>language==='RU'?(words[s]||s):s;
const say=s=>$('notice').textContent=s;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Consume each response before starting the next request: one browser socket.
let webQueue=Promise.resolve(),webQueued=0;
function webFetch(url,options){
 if(webQueued>=8)return Promise.reject(Error(language==='RU'?'Слишком много запросов. Подождите.':'Too many requests. Please wait.'));
 ++webQueued;
 const work=webQueue.then(async()=>{const r=await fetch(url,options),body=await r.arrayBuffer();return new Response(body,{status:r.status,statusText:r.statusText,headers:r.headers});});
 webQueue=work.catch(()=>{});return work.finally(()=>--webQueued);
}
const pendingReads=new Map();
let apiEpoch=0;
function api(op,values){
 if(values){++apiEpoch;pendingReads.clear();return apiRequest(op,values);}
 const key=csrf+'|'+op;if(pendingReads.has(key))return pendingReads.get(key);
 const promise=apiRequest(op).finally(()=>{if(pendingReads.get(key)===promise)pendingReads.delete(key);});pendingReads.set(key,promise);return promise;
}
async function apiRequest(op,values){
 const epoch=apiEpoch;
 const options={credentials:'same-origin',cache:'no-store'};
 if(values){options.method='POST';options.headers={'Content-Type':'text/plain;charset=UTF-8'};if(csrf)options.headers['X-CSRF-Token']=csrf;options.body=Object.entries(values).map(([k,v])=>`${k}=${encodeURIComponent(v)}\n`).join('');}
 let response,value;try{response=await webFetch('/api/'+op,options);value=await response.json();}catch(cause){throw Error(language==='RU'?'Связь потеряна. Результат не подтверждён; черновик сохранён.':'Connection lost. Result unconfirmed; draft preserved.');}
 if(response.status===503&&response.headers.get('Retry-After')){const error=Error(language==='RU'?'Web занят. Подождите и повторите вручную; изменения автоматически не повторяются.':'Web is busy. Wait and retry manually; changes are not retried automatically.');error.status=503;throw error;}
 if(!response.ok){const messages={400:['Check the entered values.','Проверьте введённые значения.'],401:['Sign in again.','Войдите повторно.'],403:['Access or password verification refused.','Доступ или проверка пароля отклонены.'],409:['Settings changed. Reopen the section before saving; your draft is still shown.','Настройки изменились. Перед сохранением откройте раздел заново; черновик остаётся на экране.'],422:['Settings refused in the current state.','Настройки отклонены в текущем состоянии.'],423:['Another operation is in progress.','Другая операция ещё выполняется.'],429:['Too many attempts. Wait one minute.','Слишком много попыток. Подождите минуту.'],503:['Service or durable storage unavailable. Result unconfirmed.','Сервис или надёжная запись недоступны. Результат не подтверждён.']};const error=Error((messages[response.status]||['Request refused.','Запрос отклонён.'])[language==='RU'?1:0]);error.status=response.status;error.validation=value.data?.validation;throw error;}
 if(value.csrf&&epoch===apiEpoch)csrf=value.csrf;value.httpStatus=response.status;return value;
}
function field(name,label,value,type='text'){return `<label>${escape(t(label))}<input name="${name}" type="${type}" value="${escape(value)}" ${type==='password'?'minlength="12" maxlength="128" autocomplete="new-password"':'required'}></label>`;}
function select(name,label,value,options){return `<label>${escape(t(label))}<select name="${name}">${options.map((v,i)=>`<option value="${i}" ${Number(value)===i?'selected':''}>${escape(t(v))}</option>`).join('')}</select></label>`;}
function collect(form){return Object.fromEntries(new FormData(form));}
function submit(form,action){form.noValidate=true;form.addEventListener('submit',async e=>{e.preventDefault();await localAction(form,()=>action(collect(form)));});}
const sections=['Overview','Ports','Network','Diagnostics','System','Help','About'];
function start(){$('logout').textContent=t('Sign out');document.documentElement.lang=language.toLowerCase();document.body.classList.remove('auth');$('nav').hidden=false;$('logout').hidden=false;$('nav').innerHTML=sections.map(s=>`<button data-page="${s}">${t(s)}</button>`).join('');$('nav').querySelectorAll('button').forEach(b=>b.onclick=()=>show(b.dataset.page));show('Overview');}
let viewGeneration=0;
async function show(name){const generation=++viewGeneration;clearInterval(networkTimer);if(typeof stopRefresh==='function')stopRefresh();page=name;say('');$('nav').classList.remove('open');$('nav').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));try{if(name==='Help'){const response=await webFetch('/help/'+language.toLowerCase()+'.html',{credentials:'same-origin',cache:'no-store'});if(!response.ok)throw Error(t('Unavailable'));const html=await response.text();if(generation===viewGeneration)content.innerHTML=html;return;}let result=await api(name.toLowerCase());if(generation!==viewGeneration)return;revision=result.revision;const data=result.data;content.innerHTML=`<h1>${t(name)}</h1>`;if(name==='Ports')ports(data);else if(name==='Network')network(data,revision);else if(name==='System')system(data,revision);else if(name==='About')content.innerHTML+=`<p>4VRS Gateway &middot; ${escape(data.version)} &middot; Moxa UC-7420-LX Plus</p><p>${language==='RU'?'Локальное управление последовательными портами Moxa.':'Local management of Moxa serial ports.'}</p><p>${language==='RU'?'Ядро':'Kernel'}: ${escape(data.kernel||t('Unavailable'))}</p><p>${language==='RU'?'Архитектура':'Architecture'}: ${escape(data.architecture||t('Unavailable'))} · ${data.word_bits} bit · ${data.big_endian?'BE':'LE'}</p>${deviceWebDescription().split('\n\n').map(p=>`<p>${escape(p)}</p>`).join('')}`;else if(name==='Diagnostics')diagnostics(data);else overview(data);}catch(e){say(e.message);}}
function ports(list){content.innerHTML+=`<div class="table"><table><thead><tr><th>${t('Ports')}</th><th>${language==='RU'?'Состояние':'State'}</th><th>UART</th><th>Transport</th><th>IP : Port</th><th></th></tr></thead><tbody>${list.map(p=>`<tr><td>P${p.id}</td><td>${t(p.enabled?'Enabled':'Disabled')}</td><td>${p.baud} / ${p.data_bits}${['N','E','O'][p.parity]}${p.stop_bits}</td><td>${['Modbus TCP','Modbus UDP','RTU/UDP','RAW TCP','RAW UDP'][p.transport]}</td><td>${p.bind}:${p.port}</td><td><button data-id="${p.id}">${language==='RU'?'Изменить':'Edit'}</button></td></tr>`).join('')}</tbody></table></div>`;content.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>editPort(list.find(p=>p.id===Number(b.dataset.id)),revision));}
function editPort(p,expected){content.innerHTML=`<h1>${t('Ports')} / P${p.id}</h1><p>${language==='RU'?'Настройки применяются только после сохранения.':'Changes apply only when you save.'}</p><form>${select('enabled','State',p.enabled,['Disabled','Enabled'])}${select('mode','Serial mode',p.mode,['RS-232','RS-485 2-wire','RS-422','RS-485 4-wire'])}${field('baud','Baud',p.baud,'number')}${field('data_bits','Data bits',p.data_bits,'number')}${select('parity','Parity',p.parity,['None','Even','Odd'])}${field('stop_bits','Stop bits',p.stop_bits,'number')}${select('transport','Transport',p.transport,['Modbus TCP','Modbus UDP','RTU/UDP','RAW TCP','RAW UDP'])}${field('bind','Bind IP',p.bind)}${field('port','TCP / UDP port',p.port,'number')}${select('special_enabled','Special baud',p.special_enabled,['Disabled','Enabled'])}${field('special_baud','Special baud value',p.special_baud,'number')}<button>${t('Save')}</button></form>`;submit(content.querySelector('form'),async values=>{expected=await saveConfiguration(content.querySelector('form'),'port',{...values,id:p.id,revision:expected});});}
function system(d,expected){content.innerHTML+=`<h2>Web Server</h2><form id="webform">${select('enabled','State',d.web_enabled,['Disabled','Enabled'])}${select('interface','Interface',d.web_interface,['LAN1','LAN2','Both'])}${select('protocol','Protocol',d.web_protocol,['HTTP','HTTPS (TLS)'])}<p class="full">${protocolHint()}</p><button>${t('Save')}</button></form><h2>${language==='RU'?'Подсветка':'Backlight'}</h2><form id="lightform">${select('enabled','Backlight',d.backlight,['Disabled','Enabled'])}<button>${t('Save')}</button></form><h2>NTP</h2><form id="ntpform">${select('enabled','NTP',d.ntp_enabled,['Disabled','Enabled'])}${field('server','Server',d.ntp_server)}<label>Interval<select name="interval">${[1,6,24].map(h=>`<option ${h===d.ntp_interval?'selected':''}>${h}</option>`).join('')}</select></label><button>${t('Save')}</button></form>`;for(const [form,op]of [['webform','web'],['lightform','backlight'],['ntpform','ntp']])submit($(form),async values=>{if(op==='web'&&Number(values.protocol)!==d.web_protocol){
 await api(op,{...values,revision:content.dataset.expected});clearInterval(networkTimer);stopRefresh();csrf='';
 const next=new URL(location.href);next.protocol=Number(values.protocol)?'https:':'http:';next.port='';next.pathname='/';next.search='';next.hash='';
 const note=feedback($(form),tr('Mode change accepted. Open the new address after startup; if startup fails, the previous mode is restored. LCD: System → Web Server.','Смена режима принята. После запуска откройте новый адрес; при ошибке запуска прежний режим восстановится. LCD: System → Web Server.'));
 const link=document.createElement('a');link.href=next.href;link.textContent=next.href;note.append(document.createElement('br'),link);return;
 }expected=await saveConfiguration($(form),op,{...values,revision:content.dataset.expected});content.dataset.expected=expected;});}
$('language').value=language;$('language').onchange=()=>{language=$('language').value;localStorage.setItem('language',language);document.documentElement.lang=language.toLowerCase();$('logout').textContent=t('Sign out');if(csrf)start();else auth().catch(e=>say(e.message));};document.body.classList.toggle('dark',localStorage.getItem('theme')==='dark');$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light');};$('toggle').onclick=()=>$('nav').classList.toggle('open');$('logout').onclick=async()=>{
 let failure;try{await api('logout',{});}catch(e){if(e.status!==401)failure=e;}
 csrf='';try{await auth();if(failure)feedback($('auth-form'),failure.message,true);}catch(e){say(e.message);}
};
