#include <stdio.h>
#include <string.h>
#include "launcher/gateway_autostart.h"
#include "launcher/gateway_startup_presentation.h"
static unsigned checks,failures;
#define CHECK(x) do{++checks;if(!(x)){++failures;printf("FAIL %u: %s\n",(unsigned)__LINE__,#x);}}while(0)
unsigned char startup_presentation_layout[sizeof(gateway_startup_presentation_t)];
typedef struct mock{int root,disable,writable,binary,executable,pid_file,matches;}mock_t;
static int exists(void*x,const char*p){mock_t*m=x;if(!strcmp(p,GATEWAY_INSTALL_ROOT))return m->root;if(!strcmp(p,GATEWAY_DISABLE_PATH))return m->disable;if(!strcmp(p,GATEWAY_BINARY_PATH))return m->binary;if(!strcmp(p,GATEWAY_PID_PATH))return m->pid_file;return 0;}
static int writable(void*x,const char*p){(void)p;return((mock_t*)x)->writable;}
static int executable(void*x,const char*p){(void)p;return((mock_t*)x)->executable;}
static int pid_read(void*x,const char*p,unsigned long*v){(void)p;*v=42;return((mock_t*)x)->pid_file?0:-1;}
static int pid_matches(void*x,unsigned long p,const char*b){(void)p;(void)b;return((mock_t*)x)->matches;}
static const gateway_autostart_ops_t ops={exists,writable,executable,pid_read,pid_matches};
static core_tick_t now(void*x){(void)x;return 1000;}
static void make_app(gateway_application_t*a,gateway_application_state_t state,unsigned progress,unsigned port,gateway_startup_event_result_t result){gateway_startup_event_t*e;memset(a,0,sizeof(*a));a->dependencies.clock=now;a->dependencies.configuration_directory="/test";a->process_state=GATEWAY_PROCESS_STARTING;a->coordinator.state=state;a->coordinator.progress_numerator=progress;a->coordinator.started_at=1;a->coordinator.event_count=1;e=&a->coordinator.events[0];e->sequence=1;e->stage=state;e->result=result;e->progress_numerator=progress;e->progress_denominator=14;e->progress_percent=progress*100U/14U;e->port_index=port;strcpy(a->platform.model,"Moxa UC-7420 Plus");strcpy(a->platform.kernel,"2.6.10");strcpy(a->platform.architecture,"ARM XScale");a->platform.word_bits=32;a->platform.big_endian=1;}
static void render_check(gateway_startup_presentation_t*p,gateway_application_t*a,const char*needle){size_t n;CHECK(gateway_startup_presentation_render(p,a,&n)==0);CHECK(n<GATEWAY_SPLASH_MAX);CHECK(strstr(p->output,needle)!=0);}
int main(void){mock_t f;gateway_application_t a;gateway_startup_presentation_t p;memset(&f,0,sizeof(f));CHECK(gateway_autostart_check(&ops,&f)==GATEWAY_AUTOSTART_STORAGE_UNAVAILABLE);f.root=1;f.disable=1;CHECK(gateway_autostart_check(&ops,&f)==GATEWAY_AUTOSTART_DISABLED);f.disable=0;CHECK(gateway_autostart_check(&ops,&f)==GATEWAY_AUTOSTART_STORAGE_READ_ONLY);f.writable=1;CHECK(gateway_autostart_check(&ops,&f)==GATEWAY_AUTOSTART_BINARY_MISSING);f.binary=1;CHECK(gateway_autostart_check(&ops,&f)==GATEWAY_AUTOSTART_BINARY_NOT_EXECUTABLE);f.executable=1;CHECK(gateway_autostart_check(&ops,&f)==GATEWAY_AUTOSTART_START);f.pid_file=1;CHECK(gateway_autostart_check(&ops,&f)==GATEWAY_AUTOSTART_STALE_PID);f.matches=1;CHECK(gateway_autostart_check(&ops,&f)==GATEWAY_AUTOSTART_ALREADY_RUNNING);gateway_startup_presentation_init(&p,GATEWAY_SPLASH_ASCII);make_app(&a,GATEWAY_APP_LOADING_CONFIGURATION,1,GATEWAY_NO_PORT,GATEWAY_EVENT_OK);render_check(&p,&a,"[#-------------------] 7%");CHECK(strstr(p.output,"4VRS Gateway")&&strstr(p.output,"v2026.01.01"));make_app(&a,GATEWAY_APP_STARTING_PORTS,7,2,GATEWAY_EVENT_SKIPPED);render_check(&p,&a,"P3 disabled");make_app(&a,GATEWAY_APP_STARTING_PORTS,8,3,GATEWAY_EVENT_FAILED);render_check(&p,&a,"P4 failed");make_app(&a,GATEWAY_APP_READY,14,GATEWAY_NO_PORT,GATEWAY_EVENT_COMPLETE);render_check(&p,&a,"Ready");CHECK(strstr(p.output,"100%"));make_app(&a,GATEWAY_APP_DEGRADED,14,GATEWAY_NO_PORT,GATEWAY_EVENT_COMPLETE);render_check(&p,&a,"Degraded");make_app(&a,GATEWAY_APP_SAFE_MODE,14,GATEWAY_NO_PORT,GATEWAY_EVENT_COMPLETE);render_check(&p,&a,"Safe Mode");make_app(&a,GATEWAY_APP_FATAL_ERROR,14,GATEWAY_NO_PORT,GATEWAY_EVENT_FAILED);render_check(&p,&a,"Fatal Error");gateway_startup_presentation_init(&p,GATEWAY_SPLASH_UTF8);make_app(&a,GATEWAY_APP_READY,14,GATEWAY_NO_PORT,GATEWAY_EVENT_COMPLETE);render_check(&p,&a,"\xe2\x96\x88");p.last_percent=80;make_app(&a,GATEWAY_APP_LOADING_CONFIGURATION,1,GATEWAY_NO_PORT,GATEWAY_EVENT_OK);render_check(&p,&a,"80%");CHECK(a.coordinator.progress_numerator==1);printf("gateway_launcher checks=%u failed=%u presentation=%u splash_max=%u\n",checks,failures,gateway_startup_presentation_bytes(),GATEWAY_SPLASH_MAX);return failures?1:0;}
